import React from "react"

/*

---------------------------------------------------------------------------
HOW TO USE IT:
---------------------------------------------------------------------------

const [captchaCode, setCaptchaCode] = React.useState("")
const [reloadCounter, setReloadCounter] = React.useState(0)

return (
        <LoginCaptcha
              height={36}
              setCaptchaCode={setCaptchaCode}
              reloadCaptchaOnUpdate={reloadCounter}
              />
        )
*/

const LoginCaptcha = ({ height, setCaptchaCode, reloadCaptchaOnUpdate }) => {
  const [captchaImage, setCaptchaImage] = React.useState(
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH5gsFEhUuuAYP2QAAAAtJREFUCNdjYAACAAAFAAHiJgWbAAAAAElFTkSuQmCC"
  )
  const captchaRef = React.useRef(null)
  const captchaImageWidth = captchaRef.current?.offsetWidth
    ? captchaRef.current?.offsetWidth + captchaRef.current?.offsetWidth * 1.2 + "px"
    : "0px"

  const generateCaptcha = () => {
    // FUNCTION TO GET A RANDOM COLOR FOR EACH CHARACTER
    const captchaRandomColor = () => {
      const r = Math.floor(Math.random() * 256)
      const g = Math.floor(Math.random() * 256)
      const b = Math.floor(Math.random() * 256)
      return "rgb(" + r + "," + g + "," + b + ")"
    }

    // FUNCTION TO DRAW A CHARACTER
    const captchaDrawCharacter = (context, valueX, character) => {
      // GETTING A RANDOM ANGLE
      const randomAngle = Math.floor(Math.random() * 60)
      let rad = (randomAngle * Math.PI) / 180

      // SETTING THE Y POSITION
      let valueY = 23

      // CHECKING A 50% POSSIBILITY TO ROTATE THE CHARACTER COUNTERCLOCKWISE
      if (Math.floor(Math.random() * 10) <= 5) {
        // ROTATING THE CHARACTER COUNTERCLOCKWISE
        rad = -rad

        // UPDATING THE CHARACTER Y POSITION
        valueY = valueY + 5
      }

      // SETTING THE CHARACTER ROTATION
      context.translate(valueX, valueY)
      context.rotate(rad)

      // SETTING A RANDOM COLOR FOR THE CHARACTER
      context.fillStyle = captchaRandomColor()

      // DRAWING THE CHARACTER
      context.fillText(character, 0, 0)

      // RESTORING THE CANVAS ROTATION
      context.rotate(-rad)
      context.translate(-valueX, -valueY)
    }

    // SETTING ALL THE AVAILABLE CHARACTERS FOR THE CAPTCHA
    const charsArray = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

    // SETTING HOW MANY CHARACTERS WILL THE CAPTCHA IS GOING TO HAVE
    const lengthOtp = 6

    // VARIABLE THAT WILL CONTAIN THE CAPTCHA CODE
    let captchaCode = null

    // SETTING A VARIABLE THAT WILL CONTAINS ALL THE CAPTCHA CHARACTERS
    const captcha = []

    // LOOPING UNTIL THE CAPTCHA IS FULLY GENERATED
    while (captcha.length < lengthOtp) {
      // GETTING A RANDOM INDEX
      const index = Math.floor(Math.random() * charsArray.length)

      // GETTING A RANDOM CHARACTER
      const randomCharacter = charsArray[index]

      // CHECKING IF THE RANDOM CHARACTER IS NOT ALREADY IN THE CAPTCHA
      if (captcha.indexOf(randomCharacter) === -1) {
        // ADDING THE RANDOM CHARACTER
        captcha.push(randomCharacter)
      }
    }

    // SAVING THE GENERATED CAPTCHA CODE
    captchaCode = captcha.join("")

    // CREATING A CANVAS
    const canvas = document.createElement("canvas")
    canvas.width = 400
    canvas.height = 34

    // SETING THE FONT NAME AND SIZE
    canvas.getContext("2d").font = "26px Arial"

    // LOOPING EVERY CHARACTER FROM THE CAPTCHA
    for (let i = 0; i < captcha.length; i++) {
      captchaDrawCharacter(canvas.getContext("2d"), i * 26 + 19, captcha[i])
    }

    // ADDING RANDOM CHARACTERS THAT WON'T BE USED AND
    // ARE ADDED TO FOOL THE BOTS THAT WILL TRY TO READ
    // THE IMAGE SOURCE GENERATED BY THIS CAPTCHA SCRIPT.
    for (let valueX = 270; valueX <= 360; valueX = valueX + 30) {
      // A 40% POSSIBILITY TO HIDE THE THIRD OR FOURTH CHARACTER
      const mustBeHidden = Math.floor(Math.random() * 10) <= 4

      captchaDrawCharacter(
        canvas.getContext("2d"),
        valueX + (valueX <= 300 ? 0 : mustBeHidden ? 999 : 0),
        charsArray[Math.floor(Math.random() * charsArray.length)]
      )
    }

    // DRAWING LINES OVER THE CHARACTERS
    for (let i = 0; i <= 5; i++) {
      canvas.getContext("2d").strokeStyle = captchaRandomColor()
      canvas.getContext("2d").beginPath()
      canvas
        .getContext("2d")
        .moveTo(Math.random() * canvas.width, Math.random() * canvas.height)
      canvas
        .getContext("2d")
        .lineTo(Math.random() * canvas.width, Math.random() * canvas.height)
      canvas.getContext("2d").stroke()
    }

    // DRAWING DOTS OVER THE CHARACTERS
    for (let i = 0; i < 30; i++) {
      const tempX = Math.random() * canvas.width
      const tempY = Math.random() * canvas.height
      canvas.getContext("2d").strokeStyle = captchaRandomColor()
      canvas.getContext("2d").beginPath()
      canvas.getContext("2d").moveTo(tempX, tempY)
      canvas.getContext("2d").lineTo(tempX + 1, tempY + 1)
      canvas.getContext("2d").stroke()
    }

    // RETURNING AN OBJECT WITH THE CAPTCHA IMAGE AND CODE
    return { captchaImage: canvas.toDataURL("data/png"), captchaCode: captchaCode }
  }

  const newCaptcha = () => {
    const captchaData = generateCaptcha()
    setCaptchaImage(captchaData.captchaImage)
    setCaptchaCode(captchaData.captchaCode)
  }

  React.useEffect(() => {
    newCaptcha()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reloadCaptchaOnUpdate])

  React.useEffect(() => {
    newCaptcha()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div
      ref={captchaRef}
      style={{
        height: height + "px",
        backgroundImage: "url(" + captchaImage + ")",
        backgroundSize: captchaImageWidth + " 100%",
        ...styles.container,
      }}
    />
  )
}

const styles = {
  container: {
    backgroundColor: "#FFFFFF",
    width: "100%",
    padding: "4px",
    margin: "2px 6px 16px 0",
    border: "1px solid #D3D3D3",
    boxSizing: "border-box",
    borderRadius: "5px",
  },
}

export default LoginCaptcha
